export const studentFields = () => {
  return [
    {
      label: "First Name",
      placeholder: "Enter first name",
      type: "text",
      required: "First name is required",
      name: "first_name",
      colSpan: "col-span-6",
    },
    {
      label: "Last Name",
      placeholder: "Enter last name",
      type: "text",
      required: "Last name is required",
      name: "last_name",
      colSpan: "col-span-6",
    },
    {
      label: "Date of Birth",
      placeholder: "Select date of birth",
      type: "date",
      required: "Date of Birth is required",
      name: "dob",
      colSpan: "col-span-6",
    },
    {
      label: "Email",
      placeholder: "Enter email address",
      type: "email",
      required: "Email Address is required",
      name: "email",
      colSpan: "col-span-6",
    },
    {
      label: "Phone Number",
      placeholder: "Enter phone number",
      type: "text",
      required: "Phone number is required",
      name: "phone",
      colSpan: "col-span-6",
    },
    {
      label: "Admission Date",
      placeholder: "Select admission date",
      type: "date",
      required: "Admission date is required",
      name: "admission_date",
      colSpan: "col-span-6",
    },
    {
      label: "Class",
      placeholder: "Enter Class ID",
      type: "text",
      required: "Class ID is required",
      name: "class_id",
      colSpan: "col-span-6",
    },
    {
      label: "Section",
      placeholder: "Enter Section ID",
      type: "text",
      required: "Section ID is required",
      name: "section_id",
      colSpan: "col-span-6",
    },
    {
      label: "Address",
      placeholder: "Enter address",
      type: "textarea",
      rows: "5",
      required: "Address is required",
      name: "address",
      colSpan: "col-span-12",
    },
    {
      label: "Add Student",
      type: "button",
      action: "submit",
      colSpan: "col-span-9",
    },
    {
      label: "Cancel",
      type: "button",
      action: "cancel",
      colSpan: "col-span-3",
    },
  ];
};
